version: "2"

services:

  app:
    build:
      context: .
    links:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "js_talks_db"
    ports:
      - "3306:3306"
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    links:
      - mysql
    ports:
      - "8081:80"
