version: "2"

services:

  app:
    build:
      context: .
    links:
      - mysql
    ports:
      - "8888:8080"

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "js_talks_db"
    ports:
      - "3306:3306"
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d
