branch-defaults:
  master:
    environment: prod
deploy:
  artifact: artefact.zip
global:
  application_name: js-talks-back
  default_ec2_keyname: mathieu.breton
  default_platform: Node.js
  default_region: eu-central-1
  profile: eb-cli
