branch-defaults:
  master:
    environment: prod
global:
  application_name: js-talks-back
  branch: null
  default_ec2_keyname: mathieu.breton
  default_platform: Node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
