# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
  jobs:
    build-job:
      working_directory: ~/repo
      docker:
        - image: circleci/node:latest-browsers
        - checkout
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
        - run: npm install
    test-job:
      requires:
        - build-job
      working_directory: ~/repo
      docker:
        - image: circleci/node:latest-browsers
        - image: circleci/mysql:latest
      steps:
        - run: npm test
        - store_artifacts:
            path: test/unit/coverage
            prefix: tests
    deploy-job:
      working_directory: ~/repo
      docker:
        - image: circleci/node:latest-browsers
      filters:
        branches:
          only: master
      requires:
        - build-job
      command: "eb deploy"