# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
      - image: circleci/mysql:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - node-modules-{{ checksum "package.json" }}
          - node-modules-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package.json" }}
      - run: npm test
      - store_artifacts:
          path: test/unit/coverage
          prefix: tests
      - run: sudo apt-get install python-pip
      - run: pip install awsebcli --upgrade --user
      - run: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then eb deploy;
            fi
