# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
  test-job:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest-browsers
      - image: circleci/mysql:latest
    steps:
      - run: npm test
      - store_artifacts:
          path: test/unit/coverage
          prefix: tests
  deploy-job:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest-browsers
    filters:
      branches:
        only: master
    steps:
      - run: eb deploy

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-job
      - test-job
          requires:
            - build-job
      - deploy-job
          requires:
            - test-job