-- MySQL Script generated by MySQL Workbench
-- ven. 19 janv. 2018 16:15:45 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema js_talks_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema js_talks_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `js_talks_db` DEFAULT CHARACTER SET utf8 ;
USE `js_talks_db` ;

-- -----------------------------------------------------
-- Table `js_talks_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `js_talks_db`.`users` ;

CREATE TABLE IF NOT EXISTS `js_talks_db`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'List of users';


-- -----------------------------------------------------
-- Table `js_talks_db`.`talks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `js_talks_db`.`talks` ;

CREATE TABLE IF NOT EXISTS `js_talks_db`.`talks` (
  `talk_id` INT NOT NULL AUTO_INCREMENT,
  `author_id` INT NULL,
  `kind` ENUM('request', 'proposal') NULL DEFAULT 'request',
  `title` VARCHAR(50) NULL,
  `description` TEXT NULL,
  `duration` ENUM('30', '60', '180') NULL DEFAULT '60',
  `scheduled_at` DATETIME NULL,
  `is_active` TINYINT NULL,
  `support` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`talk_id`),
  INDEX `fk_user_id_idx` (`author_id` ASC),
  CONSTRAINT `fkt_user_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `js_talks_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Users talks';


-- -----------------------------------------------------
-- Table `js_talks_db`.`likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `js_talks_db`.`likes` ;

CREATE TABLE IF NOT EXISTS `js_talks_db`.`likes` (
  `like_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `talk_id` INT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`like_id`),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  INDEX `fk_talk_id_idx` (`talk_id` ASC),
  CONSTRAINT `fkl_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `js_talks_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkl_talk_id`
    FOREIGN KEY (`talk_id`)
    REFERENCES `js_talks_db`.`talks` (`talk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Users like';


-- -----------------------------------------------------
-- Table `js_talks_db`.`speakers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `js_talks_db`.`speakers` ;

CREATE TABLE IF NOT EXISTS `js_talks_db`.`speakers` (
  `speaker_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `talk_id` INT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`speaker_id`),
  INDEX `fks_user_id_idx` (`user_id` ASC),
  INDEX `fks_talk_id_idx` (`talk_id` ASC),
  CONSTRAINT `fks_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `js_talks_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fks_talk_id`
    FOREIGN KEY (`talk_id`)
    REFERENCES `js_talks_db`.`talks` (`talk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'LIst of talks speakers';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
